LOG_ERRORS = 1
LOG_WARNINGS = 2
LOG_INFORMATION = 3
REACT = "React"
ANGULAR = "Angular"
VUE = "Vue"

LOG_LEVEL = LOG_INFORMATION
TECHNOLOGY = VUE
PATH_TO_SRC_FOLDER = r""
PATH_TO_INDEX_FILE = r""
PATH_TO_IMAGES_FOLDER = r""
PATH_TO_MEDIA_FOLDER = r""
